# on:定义了触发类型，当push了main分支时触发
on: [push]
env:
  GIT_USER: chaoxiaoshu-mx
  GIT_EMAIL: lekotrichia@163.com
  THEME_REPO: chaoxiaoshu-mx/vue3-ts
  THEME_BRANCH: main
  DEPLOY_REPO: git@github.com:chaoxiaoshu-mx/vue3-ts.git
  DEPLOY_BRANCH: main

# 执行的任务
jobs:
  my_job:     # 任务名称
    name: deploy to staging
    runs-on: ubuntu-latest     # 配置默认系统，github会在这个系统中执行任务，这是一个独立的服务器
    steps:    # 执行步骤
    - uses: actions/checkout@v3   # 克隆当前仓库
    - uses: actions/setup-node@v3   # 安装nodejs
      with:
        node-version: 18
    - run: npm install
    - run: npm run crowdin:sync
    - run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/                              
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL 
          git add .
          git commit -m "generated"
          git push
