# on:定义了触发类型，当push了main分支时触发
on: [push]
# 执行的任务
jobs:
  my_job:     # 任务名称
    name: deploy to staging
    runs-on: ubuntu-latest     # 配置默认系统，github会在这个系统中执行任务，这是一个独立的服务器
    steps:    # 执行步骤
    - uses: actions/checkout@v2   # 克隆当前仓库
    - uses: actions/setup-node@v3   # 安装nodejs
      with:
        node-version: 18
        java: 11
        cache: npm
    - run: npm install
    - run: crowdin download
    - run:
        git config user.name chaoxiaoshu-mx
        git config user.email leukotrichia@163.com
        git add .
        git commit -m "generated"
        git push
