# on:定义了触发类型，当push了main分支时触发
on: [push]
# 执行的任务
jobs:
  my_job:     # 任务名称
    name: deploy to staging
    runs-on: ubuntu-latest     # 配置默认系统，github会在这个系统中执行任务，这是一个独立的服务器
    steps:    # 执行步骤
    - uses: actions/checkout@v3   # 克隆当前仓库
    - uses: actions/setup-node@v3   # 安装nodejs
      with:
        node-version: 18
    - run: npm install
    - run: npm run crowdin:sync
    - run: date > generated.txt
    - run: git config user.name github-actions
    - run: git config user.email github-actions@github.com
    - run: git add .
    - run: git commit -m "generated"
    - run: git push
